#!/bin/bash

# exit immediately if a command exits with a non-zero status
set -e

# define constants
readonly CYAN='\033[0;36m'
readonly BOLD_GREEN='\033[1;32m'
readonly RESET='\033[0m'
readonly PREFIX="${CYAN}[.githooks/pre-push]${RESET}"

echo -e "${PREFIX} Running linters..."
golangci-lint run

echo -e "${PREFIX} Running tests..."
go test -v ./...

echo -e "${PREFIX} ${BOLD_GREEN}DONE!${RESET}"