version: "2"

run:
  timeout: 5m
  # tests: false

linters:
  enable:
    # default linters
    - errcheck # Errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases. (https://github.com/kisielk/errcheck)
    - govet # Vet examines Go source code and reports suspicious constructs. It is roughly the same as 'go vet' and uses its passes. (https://pkg.go.dev/cmd/vet)
    - ineffassign # Detects when assignments to existing variables are not used. (https://github.com/gordonklaus/ineffassign)
    - staticcheck # It's the set of rules from staticcheck. (https://github.com/dominikh/go-tools)
    - unused # Checks Go code for unused constants, variables, functions and types. (https://github.com/dominikh/go-tools/tree/HEAD/unused)

    # manually enabled linters
    - bodyclose # Checks whether HTTP response body is closed successfully. (https://github.com/timakin/bodyclose)
    - copyloopvar # A linter detects places where loop variables are copied. (https://github.com/karamaru-alpha/copyloopvar)
    - dupl # Detects duplicate fragments of code. (https://github.com/mibk/dupl)
    - embeddedstructfieldcheck # Embedded types should be at the top of the field list of a struct, and there must be an empty line separating embedded fields from regular fields. (https://github.com/manuelarte/embeddedstructfieldcheck)
    - err113 # Check errors handling expressions. (https://github.com/Djarvur/go-err113)
    - errorlint # Find code that can cause problems with the error wrapping scheme introduced in Go 1.13. (https://codeberg.org/polyfloyd/go-errorlint)
    - funcorder # Checks the order of functions, methods, and constructors. (https://github.com/manuelarte/funcorder)
    - gochecknoglobals # Check that no global variables exist. (https://github.com/leighmcculloch/gochecknoglobals)
    - goconst # Finds repeated strings that could be replaced by a constant. (https://github.com/jgautheron/goconst)
    - gocritic # Provides diagnostics that check for bugs, performance and style issues. (https://github.com/go-critic/go-critic)
    - godot # Check if comments end in a period. (https://github.com/tetafro/godot)
    - inamedparam # Reports interfaces with unnamed method parameters. (https://github.com/macabu/inamedparam)
    - lll # Reports long lines. (null)
    - modernize # A suite of analyzers that suggest simplifications to Go code, using modern language and library features. (https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/modernize)
    - revive # Fast, configurable, extensible, flexible, and beautiful linter for Go. Drop-in replacement of golint. (https://github.com/mgechev/revive)
  disable:
    - arangolint # Opinionated best practices for arangodb client. (https://github.com/Crocmagnon/arangolint)
    - asasalint # Check for pass []any as any in variadic func(...any). (https://github.com/alingse/asasalint)
    - asciicheck # Checks that all code identifiers does not have non-ASCII symbols in the name. (https://github.com/golangci/asciicheck)
    - bidichk # Checks for dangerous unicode character sequences. (https://github.com/breml/bidichk)
    - canonicalheader # Canonicalheader checks whether net/http.Header uses canonical header. (https://github.com/lasiar/canonicalheader)
    - clickhouselint # Detects common mistakes with the ClickHouse native Go driver API. (https://github.com/ClickHouse/clickhouse-go-linter)
    - containedctx # Containedctx is a linter that detects struct contained context.Context field. (https://github.com/sivchari/containedctx)
    - contextcheck # Check whether the function uses a non-inherited context. (https://github.com/kkHAIKE/contextcheck)
    - cyclop # Checks function and package cyclomatic complexity. (https://github.com/bkielbasa/cyclop)
    - decorder # Check declaration order and count of types, constants, variables and functions. (https://gitlab.com/bosi/decorder)
    - depguard # Go linter that checks if package imports are in a list of acceptable packages. (https://github.com/OpenPeeDeeP/depguard)
    - dogsled # Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f()). (https://github.com/alexkohler/dogsled)
    - dupword # Checks for duplicate words in the source code. (https://github.com/Abirdcfly/dupword)
    - durationcheck # Check for two durations multiplied together. (https://github.com/charithe/durationcheck)
    - errchkjson # Checks types passed to the json encoding functions. Reports unsupported types and reports occurrences where the check for the returned error can be omitted. (https://github.com/breml/errchkjson)
    - errname # Checks that sentinel errors are prefixed with the `Err` and error types are suffixed with the `Error`. (https://github.com/Antonboom/errname)
    - exhaustive # Check exhaustiveness of enum switch statements. (https://github.com/nishanths/exhaustive)
    - exhaustruct # Checks if all structure fields are initialized. (https://github.com/GaijinEntertainment/go-exhaustruct)
    - exptostd # Detects functions from golang.org/x/exp/ that can be replaced by std functions. (https://github.com/ldez/exptostd)
    - fatcontext # Detects nested contexts in loops and function literals. (https://github.com/Crocmagnon/fatcontext)
    - forbidigo # Forbids identifiers. (https://github.com/ashanbrown/forbidigo)
    - forcetypeassert # Find forced type assertions. (https://github.com/gostaticanalysis/forcetypeassert)
    - funlen # Checks for long functions. (https://github.com/ultraware/funlen)
    - ginkgolinter # Enforces standards of using ginkgo and gomega. (https://github.com/nunnatsa/ginkgolinter)
    - gocheckcompilerdirectives # Checks that go compiler directive comments (//go:) are valid. (https://github.com/leighmcculloch/gocheckcompilerdirectives)
    - gochecknoinits # Checks that no init functions are present in Go code. (null)
    - gochecksumtype # Run exhaustiveness checks on Go "sum types". (https://github.com/alecthomas/go-check-sumtype)
    - gocognit # Computes and checks the cognitive complexity of functions. (https://github.com/uudashr/gocognit)
    - gocyclo # Computes and checks the cyclomatic complexity of functions. (https://github.com/fzipp/gocyclo)
    - godoclint # Checks Golang's documentation practice (godoc). (https://github.com/godoc-lint/godoc-lint)
    - godox # Detects usage of FIXME, TODO and other keywords inside comments. (https://github.com/matoous/godox)
    - goheader # Check if file header matches to pattern. (https://github.com/denis-tingaikin/go-header)
    - gomoddirectives # Manage the use of 'replace', 'retract', and 'excludes' directives in go.mod. (https://github.com/ldez/gomoddirectives)
    - gomodguard # Allow and blocklist linter for direct Go module dependencies. This is different from depguard where there are different block types for example version constraints and module recommendations. (https://github.com/ryancurrah/gomodguard)
    - gomodguard_v2 # Allow and blocklist linter for direct Go module dependencies. This is different from depguard where there are different block types for example version constraints and module recommendations. (https://github.com/ryancurrah/gomodguard)
    - goprintffuncname # Checks that printf-like functions are named with `f` at the end. (https://github.com/golangci/go-printf-func-name)
    - gosec # Inspects source code for security problems. (https://github.com/securego/gosec)
    - gosmopolitan # Report certain i18n/l10n anti-patterns in your Go codebase. (https://github.com/xen0n/gosmopolitan)
    - grouper # Analyze expression groups. (https://github.com/leonklingele/grouper)
    - iface # Detect the incorrect use of interfaces, helping developers avoid interface pollution. (https://github.com/uudashr/iface)
    - importas # Enforces consistent import aliases. (https://github.com/julz/importas)
    - interfacebloat # A linter that checks the number of methods inside an interface. (https://github.com/sashamelentyev/interfacebloat)
    - intrange # Intrange is a linter to find places where for loops could make use of an integer range. (https://github.com/ckaznocha/intrange)
    - iotamixing # Checks if iotas are being used in const blocks with other non-iota declarations. (https://github.com/AdminBenni/iota-mixing)
    - ireturn # Accept Interfaces, Return Concrete Types. (https://github.com/butuzov/ireturn)
    - loggercheck # Checks key value pairs for common logger libraries (kitlog,klog,logr,slog,zap). (https://github.com/timonwong/loggercheck)
    - maintidx # Maintidx measures the maintainability index of each function. (https://github.com/yagipy/maintidx)
    - makezero # Find slice declarations with non-zero initial length. (https://github.com/ashanbrown/makezero)
    - mirror # Reports wrong mirror patterns of bytes/strings usage. (https://github.com/butuzov/mirror)
    - misspell # Finds commonly misspelled English words. (https://github.com/golangci/misspell)
    - mnd # An analyzer to detect magic numbers. (https://github.com/tommy-muehle/go-mnd)
    - musttag # Enforce field tags in (un)marshaled structs. (https://github.com/go-simpler/musttag)
    - nakedret # Checks that functions with naked returns are not longer than a maximum size (can be zero). (https://github.com/alexkohler/nakedret)
    - nestif # Reports deeply nested if statements. (https://github.com/nakabonne/nestif)
    - nilerr # Find the code that returns nil even if it checks that the error is not nil. (https://github.com/gostaticanalysis/nilerr)
    - nilnesserr # Reports constructs that checks for err != nil, but returns a different nil value error. (https://github.com/alingse/nilnesserr)
    - nilnil # Checks that there is no simultaneous return of `nil` error and an invalid value. (https://github.com/Antonboom/nilnil)
    - nlreturn # Checks for a new line before return and branch statements to increase code clarity. (https://github.com/ssgreg/nlreturn)
    - noctx # Detects function and method with missing usage of context.Context. (https://github.com/sonatard/noctx)
    - noinlineerr # Disallows inline error handling (`if err := ...; err != nil {`). (https://github.com/AlwxSin/noinlineerr)
    - nolintlint # Reports ill-formed or insufficient nolint directives. (https://github.com/golangci/golangci-lint/tree/HEAD/pkg/golinters/nolintlint/internal)
    - nonamedreturns # Reports all named returns. (https://github.com/firefart/nonamedreturns)
    - nosprintfhostport # Checks for misuse of Sprintf to construct a host with port in a URL. (https://github.com/stbenjam/no-sprintf-host-port)
    - paralleltest # Detects missing usage of t.Parallel() method in your Go test. (https://github.com/kunwardeep/paralleltest)
    - perfsprint # Checks that fmt.Sprintf can be replaced with a faster alternative. (https://github.com/catenacyber/perfsprint)
    - prealloc # Find slice declarations that could potentially be pre-allocated. (https://github.com/alexkohler/prealloc)
    - predeclared # Find code that shadows one of Go's predeclared identifiers. (https://github.com/nishanths/predeclared)
    - promlinter # Check Prometheus metrics naming via promlint. (https://github.com/yeya24/promlinter)
    - protogetter # Reports direct reads from proto message fields when getters should be used. (https://github.com/ghostiam/protogetter)
    - reassign # Checks that package variables are not reassigned. (https://github.com/curioswitch/go-reassign)
    - recvcheck # Checks for receiver type consistency. (https://github.com/raeperd/recvcheck)
    - rowserrcheck # Checks whether Rows.Err of rows is checked successfully. (https://github.com/golangci/rowserrcheck)
    - sloglint # Ensures consistent code style when using log/slog. (https://github.com/go-simpler/sloglint)
    - spancheck # Checks for mistakes with OpenTelemetry/Census spans. (https://github.com/jjti/go-spancheck)
    - sqlclosecheck # Checks that sql.Rows, sql.Stmt, sqlx.NamedStmt, pgx.Query are closed. (https://github.com/ryanrolds/sqlclosecheck)
    - tagalign # Check that struct tags are well aligned. (https://github.com/4meepo/tagalign)
    - tagliatelle # Checks the struct tags. (https://github.com/ldez/tagliatelle)
    - testableexamples # Linter checks if examples are testable (have an expected output). (https://github.com/maratori/testableexamples)
    - testifylint # Checks usage of github.com/stretchr/testify. (https://github.com/Antonboom/testifylint)
    - testpackage # Linter that makes you use a separate _test package. (https://github.com/maratori/testpackage)
    - thelper # Thelper detects tests helpers which do not start with the t.Helper() method. (https://github.com/kulti/thelper)
    - tparallel # Tparallel detects inappropriate usage of t.Parallel() method in your Go test codes. (https://github.com/moricho/tparallel)
    - unconvert # Remove unnecessary type conversions. (https://github.com/mdempsky/unconvert)
    - unparam # Reports unused function parameters. (https://github.com/mvdan/unparam)
    - unqueryvet # Detects SELECT * in SQL queries and SQL builders, preventing performance issues and encouraging explicit column selection. (https://github.com/MirrexOne/unqueryvet)
    - usestdlibvars # A linter that detect the possibility to use variables/constants from the Go standard library. (https://github.com/sashamelentyev/usestdlibvars)
    - usetesting # Reports uses of functions with replacement inside the testing package. (https://github.com/ldez/usetesting)
    - varnamelen # Checks that the length of a variable's name matches its scope. (https://github.com/blizzy78/varnamelen)
    - wastedassign # Finds wasted assignment statements. (https://github.com/sanposhiho/wastedassign)
    - whitespace # Whitespace is a linter that checks for unnecessary newlines at the start and end of functions, if, for, etc. (https://github.com/ultraware/whitespace)
    - wrapcheck # Checks that errors returned from external packages are wrapped. (https://github.com/tomarrell/wrapcheck)
    - wsl # Add or remove empty lines. (https://github.com/bombsimon/wsl)
    - wsl_v5 # Add or remove empty lines. (https://github.com/bombsimon/wsl)
    - zerologlint # Detects the wrong usage of `zerolog` that a user forgets to dispatch with `Send` or `Msg`. (https://github.com/ykadowak/zerologlint)
